### ISSUE TITLE
Rangerror: Invalid array length

### ISSUE THREAD

**Issue by noudilus** [kss-node/kss-node#137]
After I install kss node through the CLI and want to run the kss-node command I keep getting this error. I tried on multiple systems and also tried to clean npm cache:

RangeError: Invalid array length
    at C:\Users\name\AppData\Roaming\npm\node_modules\kss\node_modules\yargs\index.js:431:27
    at Array.forEach (native)
    at Object.Argv.self.help (C:\Users\name\AppData\Roaming\npm\node_modules\kss\node_modules\yargs\index.js:380:14)
    at Object.Argv.self.showHelp (C:\Users\name\AppData\Roaming\npm\node_modules\kss\node_modules\yargs\index.js:275:17)
    at Object.<anonymous> (C:\Users\name\AppData\Roaming\npm\node_modules\kss\bin\kss-node:167:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Anyone having this same error? What can I do about it? Thanks in advance.

**Comment by noudilus** [comment]
Thanks. I assumed that if I typed just 'kss-node' as a command I would get the command line options list. Instead of that I get the error as stated above. Everything else just works fine.

**Comment by JohnAlbin** [comment]
> if I typed just 'kss-node' as a command I would get the command line options list. 

Yep. That's exactly what I see, a list of command line options. I've tried 1.3.0 and the latest 2.x code and they both work fine.

> Also, which version are you using?

Still need an answer to this.

**Comment by bjmiller121** [comment]
I'm also seeing the same error. I'm using version 1.3.0 and get this error with any `kss-node` command including `kss-node --help`.

Here's my error message which happens to be slightly different, but still the same `RangeError: Invalid array length` error:
```
RangeError: Invalid array length
    at /usr/local/lib/node_modules/kss/node_modules/yargs/index.js:431:27
    at Array.forEach (native)
    at Object.Argv.self.help (/usr/local/lib/node_modules/kss/node_modules/yargs/index.js:380:14)
    at Object.Argv.self.showHelp (/usr/local/lib/node_modules/kss/node_modules/yargs/index.js:275:17)
    at /usr/local/lib/node_modules/kss/node_modules/yargs/index.js:461:22
    at Array.forEach (native)
    at parseArgs (/usr/local/lib/node_modules/kss/node_modules/yargs/index.js:459:27)
    at Object.Argv.Object.defineProperty.get [as argv] (/usr/local/lib/node_modules/kss/node_modules/yargs/index.js:446:36)
    at Object.<anonymous> (/usr/local/lib/node_modules/kss/bin/kss-node:109:2)
    at Module._compile (module.js:456:26)
```

**Comment by JohnAlbin** [comment]
I still can't reproduce this. I'm wondering if this is because there is a bug in a specific version of one of kss-node's dependencies and I'm using a newer (non-buggy) version of that dependency.

Can someone who is experiencing this bug post their npm-shrinkwrap.json? `npm shrinkwrap` to produce that file.

**Comment by bjmiller121** [comment]
Sure, here's mine: https://gist.github.com/bjmiller121/ea8a94407c25cb644a77

**Comment by JohnAlbin** [comment]
Thanks for posting the shrinkwrap.json file! Unfortunately, I upgraded to node.js 0.12 before I tested it out and node-sass is broken under that version of node.js, so kss-node 1.3.0 is also broken.

Can you try out kss-node 1.3.1 and see if this fixes things?

**Comment by daihuaye** [comment]
@JohnAlbin I have node v0.12.0 version. my npm-shrinkwrap file here: https://gist.github.com/daihuaye/a27247c8fb04a8c17168

I got an rangeError when I type kss-node in my terminal. Do you know what happen?

/usr/local/Cellar/nvm/0.20.0/versions/v0.12.0/lib/node_modules/kss/node_modules/yargs/index.js:431
                        + new Array(wrap - extra.length + 1).join(' ')
                          ^
RangeError: Invalid array length
    at /usr/local/Cellar/nvm/0.20.0/versions/v0.12.0/lib/node_modules/kss/node_modules/yargs/index.js:431:27
    at Array.forEach (native)
    at Object.Argv.self.help (/usr/local/Cellar/nvm/0.20.0/versions/v0.12.0/lib/node_modules/kss/node_modules/yargs/index.js:380:14)
    at Object.Argv.self.showHelp (/usr/local/Cellar/nvm/0.20.0/versions/v0.12.0/lib/node_modules/kss/node_modules/yargs/index.js:275:17)
    at Object.<anonymous> (/usr/local/Cellar/nvm/0.20.0/versions/v0.12.0/lib/node_modules/kss/bin/kss-node:177:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by mealeyst** [comment]
@JohnAlbin I seem to be having the same problem as well. I am using ndenv to manage my node versions, I've tried both v0.12.0 and v0.12.2 on a test directory. Running the command kss-node returns:
```
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at Object.<anonymous> (/Users/nps_smealey/.ndenv/versions/v0.12.2/lib/node_modules/kss/bin/kss-node:116:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
Link to the shrinkwrap file:
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at Object.<anonymous> (/Users/nps_smealey/.ndenv/versions/v0.12.2/lib/node_modules/kss/bin/kss-node:116:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by JohnAlbin** [comment]
@daihuaye Your error message is different than everyone else's. Please open a new issue as its already difficult enough to figure out this one bug in this issue.

**Comment by JohnAlbin** [comment]
I just tried @daihuaye 's  npm-shrinkwrap.json and I can't reproduce the error.

**Comment by JohnAlbin** [comment]
And I just tried @mealeyst 's npm-shrinkwrap.json and I still can't reproduce the error. :-(

**Comment by JohnAlbin** [comment]
According to http://stackoverflow.com/questions/23702115/uncaught-rangeerror-invalid-array-length-in-chrome-version-36-0-1985-5-dev-m , that error will occur when trying to create an array with a single value that is a floating point number.

If you are experiencing this error, can you tell me what `kss-node` command line flags you are using?

**Comment by JohnAlbin** [comment]
> Can you try using the latest kss-node 2.1.0 (or later) which should get you yargs 3.10.0 or later and see if that fixes the error?

I'm going to have to assume its fixed for everyone since I haven't heard a response.
