### ISSUE TITLE
Break bin/kss-node into reusable modules

### ISSUE THREAD

**Issue by nkgm** [kss-node/kss-node#138]
At the moment, there's a lot happening in `bin/kss-node`:

1. Handlebars helpers
2. Json functions
3. Page generator functions

Any build system that wishes to use `kss-node` has to replicate these functions verbatim. I think this functionality should be modularized.

**Comment by hbuchel** [comment]
@JohnAlbin Not sure if this is the best place to ask for help on this, but I've been attempting to use kss-node in my gulp setup, just like you have in the example of above. When I run the command without the custom template flag, it runs correctly; however when I append the custom template to the command I get this error:

```
Error during generation

Cannot call method 'match' of undefined
TypeError: Cannot call method 'match' of undefined
    at Object.handlebars.registerHelper.buffer (/Users/heather/code/semcog/DNN/Portals/_default/Skins/semcog/node_modules/kss/bin/kss-node:461:13)
    at Object.eval (eval at <anonymous> (/Users/heather/code/semcog/DNN/Portals/_default/Skins/semcog/node_modules/kss/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:171:23), <anonymous>:3:86)
    at Object.prog [as inverse] (/Users/heather/code/semcog/DNN/Portals/_default/Skins/semcog/node_modules/kss/node_modules/handlebars/dist/cjs/handlebars/runtime.js:168:15)
    at Object.<anonymous> (/Users/heather/code/semcog/DNN/Portals/_default/Skins/semcog/node_modules/kss/node_modules/handlebars/dist/cjs/handlebars/base.js:165:22)
    at Object.eval (eval at <anonymous> (/Users/heather/code/semcog/DNN/Portals/_default/Skins/semcog/node_modules/kss/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:171:23), <anonymous>:7:26)
    at ret (/Users/heather/code/semcog/DNN/Portals/_default/Skins/semcog/node_modules/kss/node_modules/handlebars/dist/cjs/handlebars/runtime.js:137:30)
    at ret (/Users/heather/code/semcog/DNN/Portals/_default/Skins/semcog/node_modules/kss/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:422:21)
    at generatePage (/Users/heather/code/semcog/DNN/Portals/_default/Skins/semcog/node_modules/kss/bin/kss-node:387:3)
    at /Users/heather/code/semcog/DNN/Portals/_default/Skins/semcog/node_modules/kss/bin/kss-node:336:4
    at parse (/Users/heather/code/semcog/DNN/Portals/_default/Skins/semcog/node_modules/kss/lib/kss.js:151:2)

    stderr: 
```

This is what my gulp task looks like, similar to yours: 

```
gulp.task('styleguide', shell.task([
    // kss-node [source folder of files to parse] [destination folder] --template [location of template files]
    'kss-node <%= source %> <%= destination %> --template <%= template %>'
  ], {
    templateData: {
      source:       'sass',
      destination:  'styleguide',
      template:     'styleguide-template'
    }
  }
));
```

I created the custom template by running 

```
kss-node init
```

my gulpfile, 'sass' folder, 'styleguide' folder and 'styleguide-template' folder are all siblings to eachother in my directory.

I am using version 2.0.1 and gulp 3.8.1

I thought perhaps it was this issue https://github.com/kss-node/kss-node/issues/19#issuecomment-17838126 but I've gone as far to remove all of my sass comments except for three, which are generated fine without the custom template. Any ideas of what I can look for to see where I might have gone wrong?
