### ISSUE TITLE
TypeError: rootSection.header is not a function

### ISSUE THREAD

**Issue by digitaldonkey** [kss-node/kss-node#324]
No Styleguide is generated. The script stops with:

**TypeError: rootSection.header is not a function**

Using a cloned default builde template. 

```
node_modules/kss/bin/kss --version
3.0.0-beta.14

node_modules/kss/bin/kss --verbose --source scss --destination styleguide --builder styleguide-template/guru-handlebars
...Parsing your style guide:

Building your KSS style guide!

 * KSS Source  : /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss
 * Destination : /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/styleguide
 * Builder     : /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/styleguide-template/guru-handlebars

 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/abstractions/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/__reset.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/_abstract-to-concrete.generated.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/_customer-fonts.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/_form-elements.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/_media.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/_typography.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/_logo.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/guru/_guru-browser-indicator.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/header/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/header/_logo.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/header/_page-header.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/header/_region-primary-menu.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/viewmode/viewmode/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/viewmode/viewmode/_node.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/layouts/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/layouts/_page-layout.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/main.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/module/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/variables/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/variables/_breakpoints.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/variables/_colors.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/variables/_fonts.scss
...Determining section markup:
 - 4.1: inline markup
 - Base - Form Elements: inline markup
 - Base - Media: inline markup
 - Base - Typography: inline markup
 - Components - Header - Page Header: inline markup
 - Components - Header - Region primary menu: inline markup
 - Components - Header - Site logo: inline markup
 - Components - Viewmode - Teaser: inline markup
 - Variables - Color pallete - Backgrounds: inline markup
 - Variables - Color pallete - Colors: inline markup
 - Variables - Fonts: inline markup
...Building style guide pages:
 - homepage
TypeError: rootSection.header is not a function
```

**Comment by bm2u** [comment]
@digitaldonkey with version 3.x the API has changed. Please double check your template and refer to https://github.com/kss-node/kss-node/blob/master/builder/handlebars/index.hbs. New placeholder like e. g. {{#each sections}} take place.

**Comment by digitaldonkey** [comment]
I'm cloning the template. So it should be the template deleivered with 3.0.0-beta.14. Didn't change anything (and just veryfied with the github version).






```
$ node_modules/kss/bin/kss --verbose --clone guru-handlebars
Creating a new style guide builder in /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/guru-handlebars...
You can change it as you like, and use it to build your style guide using the "builder" option


$ node_modules/kss/bin/kss --verbose --source scss --destination styleguide --builder guru-handlebars

...Parsing your style guide:

Building your KSS style guide!

 * KSS Source  : /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss
 * Destination : /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/styleguide
 * Builder     : /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/guru-handlebars

 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/abstractions/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/abstractions/_views-layouts.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/__reset.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/_abstract-to-concrete.generated.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/_customer-fonts.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/_form-elements.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/_media.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/base/_typography.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/_logo.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/_menu.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/guru/_guru-browser-indicator.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/header/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/header/_logo.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/header/_page-header.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/header/_region-primary-menu.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/viewmode/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/components/viewmode/_node.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/layouts/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/layouts/_page-layout.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/main.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/module/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/variables/__styleguide_section.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/variables/_breakpoints.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/variables/_colors.scss
 - /Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/scss/variables/_fonts.scss
...Determining section markup:
 - 4.1: inline markup
 - Base - Form Elements: inline markup
 - Base - Media: inline markup
 - Base - Typography: inline markup
 - Components - Header - Page Header: inline markup
 - Components - Header - Region primary menu: inline markup
 - Components - Header - Site logo: inline markup
 - Components - Viewmode - Teaser: inline markup
 - Variables - Color pallete - Backgrounds: inline markup
 - Variables - Color pallete - Colors: inline markup
 - Variables - Fonts: inline markup
...Building style guide pages:
 - homepage
TypeError: rootSection.header is not a function
```

**TypeError: rootSection.header is not a function** is there. 
What else could be wrong?

**Comment by digitaldonkey** [comment]
OK. The Problem was, that I had some old-Style section definitions (Styleguide X.Y) in my SCSS left, which caused the break. Replacing them with new-style (Styleguide Abstractions - Example) helped to solve. 

There should be a warning or an error or a warning with hints you to the problem!!

**Comment by JohnAlbin** [comment]
> There should be a warning or an error or a warning with hints you to the problem!!

I would add warnings if I knew what caused your problem.

Style guide references of the form `X.Y` work fine. I use them every day. So that wasn't your problem.

**Comment by JohnAlbin** [comment]
Here's the spec for the KSS syntax: https://github.com/kss-node/kss/blob/spec/SPEC.md

Additionally, the kss-node parser is forgiving and will recognize:

- Any capitalization. `styleguide` or `Styleguide` or `StyleGuide` or `StYleGuIdE`
- One or two words. `Style guide` or `Styleguide`
- Different delimiters and spacing between `styleguide` keyword and reference. `Style guide base` or `Style guide: base` or `Style guide - base` or `Style guide : base` or `Style guide - base`, etc.
- Different delimiters for the reference. `Style guide: base.bold` or `Style guide: 1.2` or `Style guide: base - bold`

**Comment by digitaldonkey** [comment]
I can reproduce if I change the Section in a single Styleguide section referer to a number while others are Word references. Literaly:  Styleguide Variables - Color pallete -->  Styleguide 4.1.4)

I didn't intentionally, but it can happen and it's kind of hard to debug. 

```
TypeError: rootSection.referenceURI is not a function
    at KssBuilderHandlebars.buildPage (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/kss/builder/base/handlebars/kss_builder_base_handlebars.js:518:35)
    at sectionRoots.forEach.rootReference (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/kss/builder/base/handlebars/kss_builder_base_handlebars.js:349:34)
    at Array.forEach (native)
    at Promise.all.then (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/kss/builder/base/handlebars/kss_builder_base_handlebars.js:348:20)
    at tryCatcher (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/them[01:43:17] 'styleguide' errored after 323 ms
[01:43:17] TypeError: rootSection.referenceURI is not a function
    at KssBuilderHandlebars.buildPage (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/kss/builder/base/handlebars/kss_builder_base_handlebars.js:518:35)
    at sectionRoots.forEach.rootReference (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/kss/builder/base/handlebars/kss_builder_base_handlebars.js:349:34)
    at Array.forEach (native)
    at Promise.all.then (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/kss/builder/base/handlebars/kss_builder_base_handlebars.js:348:20)
    at tryCatcher (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:628:18)
    at PromiseArray._resolve (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:564:26)
    at Promise._settles/guru/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:628:18)
    at PromiseArray._resolve (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:564:26)
    at Promise._settlePromise0 (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:628:18)
ePromise0 (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/tho/htdocs/drupal_guru_testing/vdd/data/drupal8/themes/guru/node_modules/bluebird/js/release/promise.js:628:18)
```

**Comment by JohnAlbin** [comment]
@digitaldonkey Thank you! That helps tremendously.
