### ISSUE TITLE
Twig builder erroring. Looking for index.hbs

### ISSUE THREAD

**Issue by jameelmoses** [kss-node/kss-node#416]
When I try to generate a style guide using a twig builder, it errors out looking for an index.hbs file. What am I doing wrong?

**KSS Version:** 3.0.0-beta.18

**Gulp Taks:**
```
gulp.task('styleguide-generate', ['styleguide-sass'], () => {

  return kss({
    title         : config.projectName + ' Styleguide',
    source        : 'src/scss',
    destination   : 'dist/styleguide',
    css           : '../css/style.css',
    builder       : 'twig-test',
    homepage      : '../../README.md',
    placeholder   : '{{modifier_class}}',
    custom        : [
      'Usage',
      'Compiled',
      'Function',
      'Definition',
      'Mixin',
      'Map',
      'Icons',
      'Colors'
    ]
  });

});
```

**Console:**
```
[09:59:46] Starting 'styleguide-generate'...
{ Error: ENOENT: no such file or directory, open '.../twig-test/index.hbs'
    at Error (native)
  cause:
   { Error: ENOENT: no such file or directory, open '.../twig-test/index.hbs'
       at Error (native)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jameel/Sites/falcore/twig-test/index.hbs' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/jameel/Sites/falcore/twig-test/index.hbs' }
[09:59:46] 'styleguide-generate' errored after 106 ms
[09:59:46] Error: ENOENT: no such file or directory, open '/Users/jameel/Sites/falcore/twig-test/index.hbs'
    at Error (native)
```

**Comment by jameelmoses** [comment]
Rolling back to 3.0.0-beta.17 resolved the issue, so something in 3.0.0-beta.18 is causing it.

**Comment by Maskim** [comment]
I've got the same error and rolling back to 3.0.0-beta.17 does not resolve it :'(

**Comment by RobLoach** [comment]
Are you using a custom builder? The builder may need updating.

**Comment by jameelmoses** [comment]
Yes, but I generated a builder using the cli.

**Comment by Maskim** [comment]
I dig a little and when I console.log the catched error in kss/builder/base/kss_builder_base.js, I see this message : TypeError: Class constructor KssBuilderBaseTwig cannot be invoked without 'new'
at new CustomKssBuilderTwig (/Users/maskim/workspace/robin_finance/cms/web/themes/custom/robin_theme/styleguide-dev/custom-builder-twig/builder.js:50:17)
    at Promise (/Users/maskim/workspace/robin_finance/cms/web/themes/custom/robin_theme/node_modules/kss/builder/base/kss_builder_base.js:200:24)

**Comment by ryuran** [comment]
@Maskim @jameelmoses Did you resolve it ?
It's from the builder generated by the CLI ?

**Comment by hsnaydd** [comment]
Hi guys;
I was getting the same error, I think the problem is related to `babel. 

I solved this error in the following way;

```js
// builder.js

/**
 * A kss-node builder that takes input files and builds a style guide using Twig
 * templates.
 */
// class KssBuilderTwig extends KssBuilderBaseTwig {
//   /**
//    * Create a builder object.
//    */
//   constructor() {
//     // First call the constructor of KssBuilderBaseTwig.
//     super();

//     // Then tell kss which Yargs-like options this builder adds.
//     this.addOptionDefinitions({
//       title: {
//         group: 'Style guide:',
//         string: true,
//         multiple: false,
//         describe: 'Title of the style guide',
//         default: 'KSS Style Guide',
//       },
//     });
//   }
// }

// module.exports = KssBuilderTwig;

module.exports = function() {
  const builder = new KssBuilderBaseTwig();

  builder.addOptionDefinitions({
    title: {
      group: 'Style guide:',
      string: true,
      multiple: false,
      describe: 'Title of the style guide',
      default: 'KSS Style Guide',
    },
  });

  return builder;
};
```

**Comment by ryuran** [comment]
@hsnaydd why babel? kss-node do not depend to babel.
Maybe node or npm version?

**Comment by hsnaydd** [comment]
May be, I'm not sure.  The error occurs when extending KssBuilderBaseTwig.

**Comment by jameelmoses** [comment]
Can confirm, @hsnaydd change worked for me and resolved the error.

**Comment by matthewbeta** [comment]
Not sure if this thread is active anymore but I have a similar issue.

My extensions were erroring saying: 

````bash
Error: An error occurred when attempting to use the "extend" directory, /Users/matthew/Projects/test/my-custom-builder/extend: Twig.extend is not a function
    at promises.push.fs.readdirAsync.then.catch (/Users/matthew/Projects/test/node_modules/kss/builder/base/kss_builder_base.js:693:27)
    at tryCatcher (/Users/matthew/Projects/test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/matthew/Projects/test/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/matthew/Projects/test/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/matthew/Projects/test/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/matthew/Projects/test/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/matthew/Projects/test/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/matthew/Projects/test/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/matthew/Projects/test/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
````

When I  log out the Twig var in one of my extensions, I get the Handlebars function. 

I removed the extensions and then fall through to the issue wheere index.hbs cannot be found:

````bash
Error: ENOENT: no such file or directory, open '/Users/matthew/Projects/1234/kss-bluegg/index.hbs
````

I went up the chain to my builder.js file and tried to log something/anything out of there but its not hitting this file at all.

I'm using the `grunt-kss` module to generate the styleguide. 

## Directory Structure 
````
public/ ________________________________# Compiled Code & Files
grunt/ _________________________________# Individual Grunt Tasks
resources/ ____________________________# Pre-Compiled Source Code & Files
|- styles/______________________________# SCSS 
|- markup/_____________________________# Templates/Partials 
|- scripts/______________________________# JS 
my-custom-builder/ ___________________# Generator for the Living Styleguide
|- helpers/ _____________________________# Extending Styleguide
|- kss-assets/ __________________________# Styleguide Assets
|- builder.js ____________________________# Styleguide Builder JS
|- index.twig ___________________________# Styleguide Builder Template
Gruntfile.js _____________________________# Main Grunt File
````

## Grunt Task
````js
module.exports = {
	options: {
		verbose: true,
		title: '<%= title %> Brand and Web Guide',
		builder: 'my-custom-builder/builder.js',
		extend: 'my-custom-builder/extend',
		custom: ['Colors', 'Logos', 'Samples'],
		css: '/styles/style.min.css'
	},
	dist: {
		src: ['<%= resources %>/styles/scss', '<%= resources %>/markup/_partials',
		dest: '<%= public %>/styleguide'
	}
};
````

## Console
````bash
Running "kss:dist" (kss) task
...Parsing your style guide:

Building your KSS style guide!

 * KSS Source  : /Users/matthew/Projects/test/resources/styles/scss, /Users/matthew/Projects/test/resources/markup/_partials
 * Destination : /Users/matthew/Projects/test/public/styleguide
 * Builder     : /Users/matthew/Projects/test/my-custom-builder
 * Extend      : /Users/matthew/Projects/test/my-custom-builder/extend

  - /Users/matthew/Projects/test/resources/styles/scss/style.scss

...Determining section markup:
 - Module.Thing: inline markup
{ Error: ENOENT: no such file or directory, open '/Users/matthew/Projects/test/my-custom-builder/index.hbs'

  cause:
   { Error: ENOENT: no such file or directory, open '/Users/matthew/Projects/test/my-custom-builder/index.hbs'

     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/matthew/Projects/test/my-custom-builder/index.hbs' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/matthew/Projects/test/my-custom-builder/index.hbs' }
Warning: ENOENT: no such file or directory, open '/Users/matthew/Projects/test/kss-bluegg/index.hbs' Use --force to continue.
Error: ENOENT: no such file or directory, open '/Users/matthew/Projects/test/my-custom-builder/index.hbs'
````

FYI I did have this working a couple of weeks ago but something seems to have broken. I've tried forcing a different version of `kss-node` required by `grunt-kss` to see if the recent update to `3.0.0-beta.19` was the issue but no dice (same issue using beta.17, 18 & 19). Having a look through the changes in beta.19, it doesn't look as though that would have broken it anyway.

🤷‍♀️

Node v8.11.1
NPM v5.6.0

**Comment by ryuran** [comment]
@matthewbeta you should return on `3.0.0-beta.18` for the moment
`3.0.0-beta.19` is have a problem to find local builder.
#469

**Comment by jameelmoses** [comment]
Can confirm the same issue with latest beta. It looks for a handlebars builder no matter what for a custom local builder

**Comment by martijndewit** [comment]
Having the same problem, using 3.0.0-beta.23. 
I can see #469 is set on fixed.
Testing with a "custom hbs" theme works but a custom twig doesn't.

**Comment by martijndewit** [comment]
@matthewbeta why do you have "builder: 'my-custom-builder/builder.js',"

I thought the builder option should be without builder.js. so in your case `builder: 'my-custom-builder',`

**Comment by ericpugh** [comment]
Still having this issue in 3.0.0-beta25, and couldn't resolve with any of the workarounds suggested here.

**Comment by prkos** [comment]
I have the same problem when using `^3.0.0-beta.14`: 

```bash
[01:56:51] Using gulpfile /var/www/html/dili/gulpfile.js
[01:56:51] Starting 'clean:css'...
[01:56:51] Starting 'clean:styleguide'...
[01:56:51] Starting 'styleguide:kss-example-chroma'...
[01:56:51] Starting 'lint:sass'...
[01:56:51] Starting 'lint:js'...
[01:56:51] Finished 'lint:js' after 134 ms
[01:56:51] Starting 'watch:js'...
[01:56:51] Finished 'watch:js' after 6.78 ms
[01:56:51] Finished 'clean:styleguide' after 275 ms
[01:56:51] Finished 'clean:css' after 280 ms
[01:56:51] Starting 'styles'...
[01:56:52] Finished 'lint:sass' after 1.13 s
[01:56:53] kss-example-chroma.twig 34.97 kB
[01:56:53] Finished 'styleguide:kss-example-chroma' after 1.38 s
[01:56:53] Starting 'styleguide'...
[01:56:53] styles.css 38.5 kB
{ Error: ENOENT: no such file or directory, open '/var/www/html/dili/node_modules/kss/builder/twig/index.hbs'
    at Error (native)
  cause: 
   { Error: ENOENT: no such file or directory, open '/var/www/html/dili/node_modules/kss/builder/twig/index.hbs'
       at Error (native)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/var/www/html/dili/node_modules/kss/builder/twig/index.hbs' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/www/html/dili/node_modules/kss/builder/twig/index.hbs' }
[01:56:53] 'styleguide' errored after 385 ms
[01:56:53] Error: ENOENT: no such file or directory, open '/var/www/html/dili/node_modules/kss/builder/twig/index.hbs'
    at Error (native)
[01:56:53] style-guide/chroma-kss-styles.css 1.2 kB
[01:56:53] style-guide/kss-only.css 463 B
[01:56:53] all files 40.16 kB
[01:56:53] Finished 'styles' after 1.77 s
```
Does using a newer version fix it? I've been using the same config before on other projects and there were no problems.
